const Cosmetics = [
  {
    id: 1,
    name: "Makeup Set",
    img: require('../assets/images/Cosmetic/cm23.png'),
    price: 3000,
    seller: "Makeup Club",
    description: "Affordable and best in the market ",
  },

  {
    id: 2,
    name: "Makeup Set",
    img: require("../assets/images/Cosmetic/cm2.webp"),
    price: 3000,
    seller: "Makeup Club",
    description: "Affordable and best in the market ",
  },
  {
    id: 3,
    name: "Makeup Set",
    img: require("../assets/images/Cosmetic/cm3.jpg"),
    price: 3000,
    seller: "Makeup Club",
    description: "Affordable and best in the market ",
  },
  {
    id: 3,
    name: "Makeup Set",
    img: require("../assets/images/Cosmetic/cm4.jfif"),
    price: 3000,
    seller: "Makeup Club",
    description: "Affordable and best in the market",
  },
  {
    id: 4,
    name: "Makeup Set",
    img: require("../assets/images/Cosmetic/cream.jfif"),
    price: 3000,
    seller: "Makeup Club",
    description: "Affordable and best in the market",
  },
  {
    id: 5,
    name: "Makeup Set",
    img: require("../assets/images/Cosmetic/foundation.jfif"),
    price: 3000,
    seller: "Makeup Club",
    description: "Affordable and best in the market",
  },

  {
    id: 6,
    name: "Makeup Set",
    img: require("../assets/images/Cosmetic/lip.jfif"),
    price: 3000,
    seller: "Makeup Club",
    description: "Affordable and best in the market",
  },
  {
    id: 7,
    name: "Makeup Set",
    img: require("../assets/images/Cosmetic/lip2.jfif"),
    price: 3000,
    seller: "Makeup Club",
    description: "Affordable and best in the market",
  },
  {
    id: 8,
    name: "Makeup Set",
    img: require("../assets/images/Cosmetic/lip3.jfif"),
    price: 3000,
    seller: "Makeup Club",
    description: "Affordable and best in the market",
  },
  {
    id: 9,
    name: "Makeup Set",
    img: require("../assets/images/CosmeticsImages/lip3.jfif"),
    price: 3000,
    seller: "Makeup Club",
    description: "Affordable and best in the market",
  },
  {
    id: 10,
    name: "Makeup Set",
    img: require("../assets/images/CosmeticsImages/paf.jfif"),
    price: 3000,
    seller: "Makeup Club",
    description: "Affordable and best in the market",
  },
];

export default Cosmetics;
