const Kitchen = [
  {
    id: 1,
    name: "All Star",
    img: require("../assets/KitchenImages/all.jpg"),
    price: 10000,
    seller: "Kitchen House",
    description: "This Show is brand new and very affordable",
  },
  {
    id: 2,
    name: "Nike Shoe",
    img: require("../assets/KitchenImages/all2.jpg"),
    price: 100000,
    seller: "Kitchen House",
    description: "This Show is brand new and very affordable",
  },
  {
    id: 3,
    name: " Shoe",
    img: require("../assets/KitchenImages/all3.jpg"),
    price: 10000,
    seller: "Kitchen House",
    description: "This Show is brand new and very affordable",
  },

  {
    id: 4,
    name: "Nike shoe",
    img: require("../assets/KitchenImages/pan.jpg"),
    price: 10000,
    seller: "Kitchen House",
    description: "This Show is brand new and very affordable",
  },
  {
    id: 5,
    name: "Classic Shoe",
    img: require("../assets/KitchenImages/pan2.jpg"),
    price: 20000,
    seller: "Kitchen House",
    description: "This Show is brand new and very affordable",
  },

  {
    id: 6,
    name: "Shoe",
    img: require("../assets/KitchenImages/pot.jpg"),
    price: 10000,
    seller: "Kitchen House",
    description: "This Show is brand new and very affordable",
  },
  {
    id: 7,
    name: "Shoe",
    img: require("../assets/KitchenImages/spoon.jpg"),
    price: 10000,
    seller: "Kitchen House",
    description: "This Show is brand new and very affordable",
  },
  {
    id: 8,
    name: "Vapor",
    img: require("../assets/KitchenImages/pot2.jpg"),
    price: 10000,
    seller: "Kitchen House",
    description: "This Show is brand new and very affordable",
  },
  {
    id: 9,
    name: "vans",
    img: require("../assets/KitchenImages/spoon2.jpg"),
    price: 10000,
    seller: "Kitchen House",
    description: "This Show is brand new and very affordable",
  },
  {
    id: 10,
    name: "Classic Shoe",
    img: require("../assets/KitchenImages/knife.jpg"),
    price: 10000,
    seller: "Kitchen House",
    description: "This Show is brand new and very affordable",
  },
];
